// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_500 = "CgkIvv-33qgEEAIQBA"; // <GPGSID>
        public const string achievement_2000 = "CgkIvv-33qgEEAIQCA"; // <GPGSID>
        public const string achievement_first_try = "CgkIvv-33qgEEAIQAw"; // <GPGSID>
        public const string achievement_1500 = "CgkIvv-33qgEEAIQBw"; // <GPGSID>
        public const string achievement_300 = "CgkIvv-33qgEEAIQAg"; // <GPGSID>
        public const string leaderboard_ranks = "CgkIvv-33qgEEAIQAQ"; // <GPGSID>
        public const string achievement_1000 = "CgkIvv-33qgEEAIQBg"; // <GPGSID>
        public const string achievement_all_clear = "CgkIvv-33qgEEAIQCw"; // <GPGSID>
        public const string achievement_3000 = "CgkIvv-33qgEEAIQCg"; // <GPGSID>
        public const string achievement_750 = "CgkIvv-33qgEEAIQBQ"; // <GPGSID>
        public const string achievement_2500 = "CgkIvv-33qgEEAIQCQ"; // <GPGSID>

}

